version: '3.8'

services:
  parser:
    build: .
    ports:
      - "3454:3454"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - PROJECT_USER=${PROJECT_USER}
      - PROJECT_PASSWORD=${PROJECT_PASSWORD}
      - DB_SSL_MODE=${DB_SSL_MODE}
    restart: always

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PROJECT_USER=${PROJECT_USER}
      - PROJECT_PASSWORD=${PROJECT_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: always

volumes:
  pgdata:
